from .harvard import Harvard
from .cmu import CMU
from .uf import UF
from .uiuc import UIUC
from .unl import UNL
from .duke import Duke
from .yale import Yale
from .skidmore import Skidmore
from .gvsu import GVSU
from .amherst import Amherst
